name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x
    - name: Restore dependencies
      run: dotnet restore -s https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test tests/CallingServer.Extension.Tests/ --no-build --verbosity normal -p:ParallelizeTestCollections=false